Repository etalab/geo.api.gouv.fr, pull requests merged in 2018-02, with the labels that each got.

#18 Suppression du déploiement GitHub Pages
  .circleci/config.yml
  package.json
  yarn.lock
Labels: build-process

#19 Nouvelle route /docs
  components/header.js
  components/home/features.js
  pages/docs/communes.js
  pages/docs/departements.js
  pages/docs/regions.js
Labels: bug

#23 Nouvel exemple "Liste des régions"
  components/regions/examples/regions-list.js
  components/regions/regions.js
Labels: enhancement
